### ISSUE TITLE
Error on connection to remote Nrepl when no internet connection

### ISSUE THREAD

**Issue by ClemensFMN** [jasongilman/proto-repl#91]
I start a headless repl via `lein repl :headless` and connect from atom via `Remote Nrepl Connection`. This works as long as my internet connection is working. If I disable it, I get the following exception (I replaced my username with ###).

Proto-repl is 1.1.7; atom is 1.6.0

`
Uncaught TypeError: Cannot read property 'constructor' of null
C:\Users\###\.atom\packages\proto-repl\node_modules\jg-nrepl-client\node_modules\bencode\lib\encode.js:31
Hide Stack Trace
TypeError: Cannot read property 'constructor' of null
    at Function.encode._encode (C:\Users\###\.atom\packages\proto-repl\node_modules\jg-nrepl-client\node_modules\bencode\lib\encode.js:31:11)
    at Function.encode.dict (C:\Users\###\.atom\packages\proto-repl\node_modules\jg-nrepl-client\node_modules\bencode\lib\encode.js:80:12)
    at Function.encode._encode (C:\Users\###\.atom\packages\proto-repl\node_modules\jg-nrepl-client\node_modules\bencode\lib\encode.js:33:18)
    at Object.encode (C:\Users\###\.atom\packages\proto-repl\node_modules\jg-nrepl-client\node_modules\bencode\lib\encode.js:9:10)
    at nreplSend (C:\Users\###\.atom\packages\proto-repl\node_modules\jg-nrepl-client\src\nrepl-client.js:112:26)
    at cljEval (C:\Users\###\.atom\packages\proto-repl\node_modules\jg-nrepl-client\src\nrepl-client.js:164:23)
    at NReplConnection.module.exports.NReplConnection.sendCommand (file:///C:/Users/###/.atom/packages/proto-repl/lib/process/nrepl-connection.coffee:139:5)
    at RemoteReplProcess.module.exports.RemoteReplProcess.sendCommand (file:///C:/Users/###/.atom/packages/proto-repl/lib/process/remote-repl-process.coffee:26:11)
    at Repl.module.exports.Repl.executeCode (file:///C:/Users/###/.atom/packages/proto-repl/lib/repl.coffee:238:14)
    at Object.module.exports.ProtoRepl.executeCode (file:///C:/Users/###/.atom/packages/proto-repl/lib/proto-repl.coffee:301:12)
    at Object.module.exports.ProtoRepl.loadCurrentFile (file:///C:/Users/###/.atom/packages/proto-repl/lib/proto-repl.coffee:523:10)
    at atom-workspace.subscriptions.add.atom.commands.add.proto-repl:load-current-file (file:///C:/Users/###/.atom/packages/proto-repl/lib/proto-repl.coffee:117:43)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (D:\Atom\resources\app.asar\src\command-registry.js:260:29)
    at D:\Atom\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (D:\Atom\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:570:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (D:\Atom\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:378:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (D:\Atom\resources\app.asar\src\window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (D:\Atom\resources\app.asar\src\window-event-handler.js:3:61)
The error was thrown from the proto-repl package.
`

**Comment by jasongilman** [comment]
I found that this wasn't correctly handling errors when trying to connect to nREPL. I marked this one as fixed but I'm not sure if this actually does solve your problem since you should be able to connect to a local nREPL if the connection is working. I pushed the new version. Give it a try and see if it clears up your problem or if you're seeing some other issue now.

**Comment by ClemensFMN** [comment]
Thanks for the fast response. In case of no internet connection, it still throws an error when connecting to localhost:

`
proto-repl: connection error
Error: getaddrinfo ENOENT localhost:50152
`

However, if I connect to 127.0.0.1, then everything works fine. But maybe this is related with my computer's settings (localhost not being resolved)?
